don't create empty configmaps
bcgov/helm-charts pull request #44
Opened 2024-10-09 19:25 UTC by rustyjux

tested with `helm upgrade cert-check charts/generic-api/.` on b8840c-dev (DR)

2024-10-09 23:31 UTC, Elson9 approved these changes

2024-10-10 00:18 UTC, ikethecoder requested changes

2024-10-10 00:18 UTC, ikethecoder commented on charts/generic-api/templates/configmap.yaml
> +{{- if .Values.config }}
The default value for `config` is `[]`.  Did you check that this IF statement returns false in the case of an empty array?

2024-10-10 15:12 UTC, rustyjux commented
Yep, it does. I tested the changes with `cert-check` on dev on DR using `helm upgrade` locally.

From: ike thecoder ***@***.***>
Sent: Wednesday, October 9, 2024 5:19 PM
To: bcgov/helm-charts ***@***.***>
Cc: Vinegar, Russell CITZ:EX ***@***.***>; Author ***@***.***>
Subject: Re: [bcgov/helm-charts] don't create empty configmaps (PR #44)

[EXTERNAL] This email came from an external source. Only open attachments or links that you are expecting from a known sender.


@ikethecoder requested changes on this pull request.

________________________________

In charts/generic-api/templates/configmap.yaml<https://github.com/bcgov/helm-charts/pull/44#discussion_r1794203168>:

> @@ -1,3 +1,4 @@

+{{- if .Values.config }}

The default value for config is []. Did you check that this IF statement returns false in the case of an empty array?

-
Reply to this email directly, view it on GitHub<https://github.com/bcgov/helm-charts/pull/44#pullrequestreview-2358275894>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AJGMSN6E7LVWJDKEQZKIJFDZ2XBWNAVCNFSM6AAAAABPVHGA7SVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNJYGI3TKOBZGQ>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2024-10-10 16:40 UTC, ikethecoder approved these changes

2024-10-10 16:40 UTC, merged